"""Sales agent prompts package — re-exports for backward compatibility."""

from .research_prompts import (
    AGGREGATED_ANSWER_TAG,
    CAMPAIGN_SIGNALS_PROMPT,
    COMPLIANCE_PROMPT,
    ECOSYSTEM_PROMPT,
    EXECUTIVE_PROMPT,
    FIRMOGRAPHICS_PROMPT,
    GEOGRAPHIC_PROMPT,
    GROWTH_SIGNALS_PROMPT,
    MARKET_PROMPT,
    PLAN_REACT_RESEARCH_BLOCK,
    PROCUREMENT_PROMPT,
    RESEARCH_GUIDELINES,
    RISK_SIGNALS_PROMPT,
    STRATEGY_PROMPT,
    TECH_STACK_PROMPT,
)
from .synthesis_prompts import ALIGNMENT_PROMPT, COLT_DETAILS, REPORT_COMPILER_PROMPT

__all__ = [
    "AGGREGATED_ANSWER_TAG",
    "RESEARCH_GUIDELINES",
    "PLAN_REACT_RESEARCH_BLOCK",
    "GROWTH_SIGNALS_PROMPT",
    "RISK_SIGNALS_PROMPT",
    "CAMPAIGN_SIGNALS_PROMPT",
    "FIRMOGRAPHICS_PROMPT",
    "GEOGRAPHIC_PROMPT",
    "EXECUTIVE_PROMPT",
    "STRATEGY_PROMPT",
    "COMPLIANCE_PROMPT",
    "MARKET_PROMPT",
    "ECOSYSTEM_PROMPT",
    "TECH_STACK_PROMPT",
    "PROCUREMENT_PROMPT",
    "COLT_DETAILS",
    "ALIGNMENT_PROMPT",
    "REPORT_COMPILER_PROMPT",
]
