"""Minimal Settings env for tests (applied via MonkeyPatch before src imports)."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _pytest.monkeypatch import MonkeyPatch

# String values only — matches pydantic-settings env parsing.
TEST_SETTINGS_ENV: dict[str, str] = {
    "DOTENV_DISABLE": "true",
    "APP_NAME": "Sales Research API",
    "APP_VERSION": "1.0.0",
    "API_PREFIX": "/api/v1",
    "DEBUG": "true",
    "IS_LOCAL": "true",
    "HOST": "127.0.0.1",
    "PORT": "8000",
    "WORKERS": "1",
    "LOG_LEVEL": "DEBUG",
    "AGENT_EVENT_LOG_VERBOSE": "false",
    "GOOGLE_CLOUD_PROJECT": "test-project",
    "GOOGLE_CLOUD_LOCATION": "europe-west1",
    "GOOGLE_GENAI_USE_VERTEXAI": "true",
    "GOOGLE_CLOUD_QUOTA_PROJECT": "test-project",
    "BIGQUERY_DATASET": "test_dataset",
    "BIGQUERY_TABLE": "research_requests",
    "BIGQUERY_USERS_TABLE": "users",
    "BIGQUERY_COST_ATTRIBUTION_TABLE": "cost_attribution",
    "BIGQUERY_AGENT_TELEMETRY_TABLE": "agent_telemetry",
    "BIGQUERY_CATALOG_JOBS_TABLE": "catalog_build_jobs",
    "SECRET_KEY": "test-secret-key-for-unit-tests-only",
    "ALGORITHM": "HS256",
    "ACCESS_TOKEN_EXPIRE_MINUTES": "30",
    "PROMPT_TEMPLATE_VERSION": "v1.0",
    "GCS_BUCKET_NAME": "test-bucket",
    "GCS_SIGNED_URL_EXPIRATION_HOURS": "1",
    "GCS_PARENT_FOLDER": "research",
    "CORS_ALLOW_ORIGINS": '["*"]',
    "CORS_ALLOW_CREDENTIALS": "true",
    "CORS_ALLOW_METHODS": '["*"]',
    "CORS_ALLOW_HEADERS": '["*"]',
    "OTEL_ENABLED": "false",
    "OTEL_SERVICE_NAME": "sales-agent-api-test",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
    "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
    "OTEL_RESOURCE_ATTRIBUTES": "service.name=test",
    "OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED": "false",
    "OTEL_SEMCONV_STABILITY_OPT_IN": "gen_ai_latest_experimental",
    "OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT": "EVENT_ONLY",
    "ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS": "false",
    "GEMINI_MODEL": "gemini-2.5-pro",
    "SEARCH_AGENT_MODEL": "gemini-2.5-flash",
    "RESEARCH_STATUS_MIN_UPDATE_INTERVAL_SECONDS": "5.0",
    "GEMINI_RETRY_ATTEMPTS": "3",
    "GEMINI_RETRY_INITIAL_DELAY": "5",
    "GEMINI_RETRY_MAX_DELAY": "120",
    "GEMINI_RETRY_EXP_BASE": "2",
    "GEMINI_RETRY_JITTER": "1",
    "GEMINI_RETRY_STATUS_CODES": "[408,429,500]",
    "GEMINI_COST_PER_1K_INPUT_TOKENS": "0.00125",
    "GEMINI_COST_PER_1K_OUTPUT_TOKENS": "0.01",
    "EVALUATOR_MODEL": "gemini-2.5-flash",
    "AGENT_RETRY_ATTEMPTS": "3",
    "AGENT_RETRY_WAIT_FIXED": "2",
    "JOB_ID_PREFIX": "job_",
    "CATALOG_JOB_ID_PREFIX": "cat_",
    "RESEARCH_INIT_STEP_LABEL": "Initializing research",
    "RESEARCH_INIT_PROGRESS": "5",
    "RESEARCH_UPLOAD_STEP_LABEL": "Uploading artifacts",
    "RESEARCH_UPLOAD_PROGRESS": "92",
    "RESEARCH_EVAL_STEP_LABEL": "Running quality evaluation",
    "RESEARCH_EVAL_PROGRESS": "97",
    "SAFETY_HARASSMENT_THRESHOLD": "BLOCK_MEDIUM_AND_ABOVE",
    "SAFETY_HATE_SPEECH_THRESHOLD": "BLOCK_MEDIUM_AND_ABOVE",
    "SAFETY_SEXUAL_THRESHOLD": "BLOCK_LOW_AND_ABOVE",
    "SAFETY_DANGEROUS_THRESHOLD": "BLOCK_ONLY_HIGH",
    "SAFETY_LOGGING_ENABLED": "true",
    "OUTPUT_GUARDRAIL_HALLUCINATION_MODEL": "gemini-2.5-flash",
    "OUTPUT_GUARDRAIL_MIN_SECTIONS": "8",
    "OUTPUT_GUARDRAIL_MAX_RETRIES": "2",
    "OUTPUT_GUARDRAIL_HALLUCINATION_BLOCK_THRESHOLD": "5",
    "VECTOR_SEARCH_INDEX_ID": "123",
    "VECTOR_SEARCH_INDEX_ENDPOINT_ID": "456",
    "VECTOR_SEARCH_DEPLOYED_INDEX_ID": "test_index",
    "VECTOR_SEARCH_EMBEDDING_MODEL": "text-embedding-004",
    "VECTOR_SEARCH_NUM_NEIGHBORS": "10",
    "VECTOR_SEARCH_BUCKET": "test-vector-bucket",
    "VECTOR_SEARCH_CATALOG_ROOT": "colt-product-catalog",
    "VECTOR_SEARCH_CHUNK_SIZE": "900",
    "VECTOR_SEARCH_CHUNK_OVERLAP": "120",
    "VECTOR_SEARCH_CHUNK_ID_PREFIX": "colt_catalog_chunk_",
    "VECTOR_SEARCH_EMBEDDING_DIMENSIONS": "768",
    "VECTOR_SEARCH_EMBEDDING_BATCH_SIZE": "16",
    "VECTOR_SEARCH_LOCAL_BUILD_DIR": "out/vector-index",
    "VECTOR_SEARCH_INDEX_DISPLAY_NAME": "test_index",
    "VECTOR_SEARCH_ENDPOINT_DISPLAY_NAME": "test-endpoint",
    "VECTOR_SEARCH_DISTANCE_MEASURE_TYPE": "DOT_PRODUCT_DISTANCE",
    "VECTOR_SEARCH_APPROXIMATE_NEIGHBORS_COUNT": "10",
    "VECTOR_SEARCH_LEAF_NODE_EMBEDDING_COUNT": "1000",
    "VECTOR_SEARCH_LEAF_NODES_TO_SEARCH_PERCENT": "7.0",
    "VECTOR_SEARCH_DEPLOY_MACHINE_TYPE": "e2-standard-2",
    "VECTOR_SEARCH_DEPLOY_MIN_REPLICAS": "1",
    "VECTOR_SEARCH_DEPLOY_MAX_REPLICAS": "1",
    "VECTOR_SEARCH_INDEX_UPDATE_POLL_INTERVAL_SEC": "30",
    "VECTOR_SEARCH_INDEX_UPDATE_TIMEOUT_SEC": "1800",
}


def apply_test_settings_env(monkeypatch: MonkeyPatch) -> None:
    """Apply test env vars before importing modules that instantiate Settings."""
    for key, value in TEST_SETTINGS_ENV.items():
        monkeypatch.setenv(key, value)
