"""Minimal Settings env for tests (applied via MonkeyPatch before src imports)."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _pytest.monkeypatch import MonkeyPatch

# String values only — matches pydantic-settings env parsing.
TEST_SETTINGS_ENV: dict[str, str] = {
    "DOTENV_DISABLE": "true",
    "APP_NAME": "Sales Research API",
    "APP_VERSION": "1.0.0",
    "API_PREFIX": "/api/v1",
    "DEBUG": "true",
    "IS_LOCAL": "true",
    "HOST": "127.0.0.1",
    "PORT": "8000",
    "WORKERS": "1",
    "LOG_LEVEL": "DEBUG",
    "AGENT_EVENT_LOG_VERBOSE": "false",
    "APP_ROLE": "",
    "API_USE_BACKGROUND_PIPELINE": "true",
    "CLOUD_TASKS_PROJECT": "test-project",
    "CLOUD_TASKS_LOCATION": "europe-west1",
    "CLOUD_TASKS_QUEUE": "research-jobs",
    "CLOUD_TASKS_WORKER_URL": "http://127.0.0.1:8001/internal/tasks/research",
    "CLOUD_TASKS_OIDC_SERVICE_ACCOUNT": "test-tasks-sa@test-project.iam.gserviceaccount.com",
    "CLOUD_TASKS_DISPATCH_DEADLINE_SECONDS": "3600",
    "WORKER_OIDC_AUDIENCE": "",
    "WORKER_SKIP_OIDC_VERIFICATION": "true",
    "GOOGLE_CLOUD_PROJECT": "test-project",
    "GOOGLE_CLOUD_LOCATION": "europe-west1",
    "GOOGLE_GENAI_USE_VERTEXAI": "true",
    "GOOGLE_CLOUD_QUOTA_PROJECT": "test-project",
    "BIGQUERY_DATASET": "test_dataset",
    "BIGQUERY_TABLE": "research_requests",
    "BIGQUERY_COST_ATTRIBUTION_TABLE": "cost_attribution",
    "BIGQUERY_AGENT_TELEMETRY_TABLE": "agent_telemetry",
    "BIGQUERY_USER_FEEDBACK_TABLE": "users_feedback",
    "FIRESTORE_DATABASE": "(default)",
    "FIRESTORE_SEARCH_CACHE_COLLECTION": "search_cache",
    "SECRET_KEY": "test-secret-key-for-unit-tests-only",
    "ALGORITHM": "HS256",
    "ACCESS_TOKEN_EXPIRE_MINUTES": "30",
    "PROMPT_TEMPLATE_VERSION": "v1.0",
    "IAP_AUDIENCE": "",
    "HUB_IAP_AUDIENCE": "",
    "SALES_REQUIRED_GROUP": "ai-salesagent-users",
    "GCS_BUCKET_NAME": "test-bucket",
    "GCS_SIGNED_URL_EXPIRATION_HOURS": "1",
    "GCS_PARENT_FOLDER": "research",
    "CORS_ALLOW_ORIGINS": '["*"]',
    "CORS_ALLOW_CREDENTIALS": "true",
    "CORS_ALLOW_METHODS": '["*"]',
    "CORS_ALLOW_HEADERS": '["*"]',
    "OTEL_ENABLED": "false",
    "OTEL_SERVICE_NAME": "sales-agent-api-test",
    "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:4317",
    "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
    "OTEL_RESOURCE_ATTRIBUTES": "service.name=test",
    "OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED": "false",
    "OTEL_SEMCONV_STABILITY_OPT_IN": "gen_ai_latest_experimental",
    "OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT": "EVENT_ONLY",
    "ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS": "false",
    "LLM_MODEL": "gemini-3.5-flash",
    "SEARCH_MODEL": "gemini-3.5-flash",
    "RESEARCH_STATUS_MIN_UPDATE_INTERVAL_SECONDS": "5.0",
    "GEMINI_RETRY_ATTEMPTS": "3",
    "GEMINI_RETRY_INITIAL_DELAY": "5",
    "GEMINI_RETRY_MAX_DELAY": "120",
    "GEMINI_RETRY_EXP_BASE": "2",
    "GEMINI_RETRY_JITTER": "1",
    "GEMINI_RETRY_STATUS_CODES": "[408,429,500]",
    "EVALUATOR_MODEL": "gemini-3.5-flash",
    "AGENT_RETRY_ATTEMPTS": "3",
    "AGENT_RETRY_WAIT_FIXED": "2",
    "JOB_ID_PREFIX": "job_",
    "RESEARCH_INIT_STEP_LABEL": "Initializing research",
    "RESEARCH_INIT_PROGRESS": "5",
    "RESEARCH_UPLOAD_STEP_LABEL": "Uploading artifacts",
    "RESEARCH_UPLOAD_PROGRESS": "92",
    "RESEARCH_EVAL_STEP_LABEL": "Running quality evaluation",
    "RESEARCH_EVAL_PROGRESS": "97",
    "SAFETY_HARASSMENT_THRESHOLD": "BLOCK_MEDIUM_AND_ABOVE",
    "SAFETY_HATE_SPEECH_THRESHOLD": "BLOCK_MEDIUM_AND_ABOVE",
    "SAFETY_SEXUAL_THRESHOLD": "BLOCK_LOW_AND_ABOVE",
    "SAFETY_DANGEROUS_THRESHOLD": "BLOCK_ONLY_HIGH",
    "SAFETY_LOGGING_ENABLED": "true",
    "OUTPUT_GUARDRAIL_HALLUCINATION_MODEL": "gemini-2.5-flash",
    "OUTPUT_GUARDRAIL_MIN_SECTIONS": "8",
    "OUTPUT_GUARDRAIL_MAX_RETRIES": "2",
    "OUTPUT_GUARDRAIL_HALLUCINATION_BLOCK_THRESHOLD": "5",
}


def apply_test_settings_env(monkeypatch: MonkeyPatch) -> None:
    """Apply test env vars before importing modules that instantiate Settings."""
    for key, value in TEST_SETTINGS_ENV.items():
        monkeypatch.setenv(key, value)
