"""Sales agent prompts package."""

from .prompt_common import (
    AGGREGATED_ANSWER_TAG,
    PLAN_REACT_RESEARCH_BLOCK,
    RESEARCH_GUIDELINES,
)
from .synthesis_prompts import ALIGNMENT_PROMPT, COLT_DETAILS, REPORT_COMPILER_PROMPT
from .synthesis_research_prompts import RESEARCH_SYNTHESIZER_PROMPT

__all__ = [
    "AGGREGATED_ANSWER_TAG",
    "RESEARCH_GUIDELINES",
    "PLAN_REACT_RESEARCH_BLOCK",
    "COLT_DETAILS",
    "ALIGNMENT_PROMPT",
    "REPORT_COMPILER_PROMPT",
    "RESEARCH_SYNTHESIZER_PROMPT",
]
