"""Research prompt compatibility re-exports."""

from .company_prompts import (
    EXECUTIVE_PROMPT,
    FIRMOGRAPHICS_PROMPT,
    GEOGRAPHIC_PROMPT,
)
from .prompt_common import (
    AGGREGATED_ANSWER_TAG,
    PLAN_REACT_RESEARCH_BLOCK,
    RESEARCH_GUIDELINES,
)
from .signal_prompts import (
    CAMPAIGN_SIGNALS_PROMPT,
    GROWTH_SIGNALS_PROMPT,
    RISK_SIGNALS_PROMPT,
)
from .strategy_market_prompts import (
    COMPLIANCE_PROMPT,
    ECOSYSTEM_PROMPT,
    MARKET_PROMPT,
    PROCUREMENT_PROMPT,
    STRATEGY_PROMPT,
    TECH_STACK_PROMPT,
)

__all__ = [
    "AGGREGATED_ANSWER_TAG",
    "PLAN_REACT_RESEARCH_BLOCK",
    "RESEARCH_GUIDELINES",
    "FIRMOGRAPHICS_PROMPT",
    "GEOGRAPHIC_PROMPT",
    "EXECUTIVE_PROMPT",
    "STRATEGY_PROMPT",
    "COMPLIANCE_PROMPT",
    "MARKET_PROMPT",
    "ECOSYSTEM_PROMPT",
    "TECH_STACK_PROMPT",
    "PROCUREMENT_PROMPT",
    "GROWTH_SIGNALS_PROMPT",
    "RISK_SIGNALS_PROMPT",
    "CAMPAIGN_SIGNALS_PROMPT",
]
