"""ADK runner lifecycle for sales research jobs."""

from __future__ import annotations

from typing import Any

from google.adk.agents.run_config import RunConfig
from google.adk.artifacts.in_memory_artifact_service import InMemoryArtifactService
from google.adk.memory.in_memory_memory_service import InMemoryMemoryService
from google.adk.runners import Runner
from google.genai import types
from .agent.session_service_factory import build_session_service
from .agent.sales.agent import create_sales_agent_app
from .agent.session_ids import runner_session_id
from ...core.config import settings
from ...core.exceptions import AgentOutputError, ServiceError
from ...core.logging_config import logger
from ...repositories.bigquery_repository import BigQueryRepository
from .agent.utils.agent import log_event
from .agent.utils.agent_pipeline import run_runner_with_per_agent_retry
from ...utils.tracing import job_attrs, traced
from .progress import ResearchProgressTracker


class ResearchRunnerService:
    """Run the SalesAgent ADK graph and stream progress to BigQuery."""

    def __init__(
        self,
        bigquery_repository: BigQueryRepository,
        progress_tracker: ResearchProgressTracker | None = None,
    ) -> None:
        self._bigquery_repo = bigquery_repository
        self._progress = progress_tracker or ResearchProgressTracker(
            bigquery_repository
        )

    @traced("research.adk.run", attributes=job_attrs)
    async def run(
        self,
        job_id: str,
        company_name: str,
        attempt: int = 0,
    ) -> tuple[str, dict]:
        """Run the SalesAgent and return the final report and session state."""
        from opentelemetry import trace

        span = trace.get_current_span()
        span.set_attribute("research.session_id", runner_session_id(job_id, attempt))
        app = create_sales_agent_app()
        session_service = build_session_service()
        runner = Runner(
            app=app,
            artifact_service=InMemoryArtifactService(),
            session_service=session_service,
            memory_service=InMemoryMemoryService(),
        )

        session = await self._get_or_create_runner_session(
            runner, app, job_id, company_name, attempt
        )

        await self.run_agents(runner, session, job_id, company_name, app)

        session = await runner.session_service.get_session(
            app_name=app.name,
            user_id="api_user",
            session_id=session.id,
        )
        final_report = session.state.get("final_report", "")

        if not final_report:
            raise ServiceError("No final report generated by SalesAgent")

        logger.info(
            f"Retrieved final report for job {job_id}, length: {len(final_report)}"
        )
        span.set_attribute("research.final_report_length", len(final_report))
        return final_report, session.state

    @traced("research.adk.runner.lifecycle", attributes=job_attrs)
    async def run_agents(
        self,
        runner: Runner,
        session: Any,
        job_id: str,
        company_name: str,
        app: Any,
    ) -> None:
        """Execute the agent run with per-agent output validation and resume retries."""
        run_config = RunConfig()

        all_agents = self._get_all_agents(app.root_agent)
        total_agents = len(all_agents)
        agent_descriptions = {a.name: a.description for a in all_agents}
        completed_agents: set[str] = set()

        status_write_state: dict[str, Any] = {
            "last_progress": None,
            "last_step": None,
            "last_write_ts": 0.0,
            "seen_authors": set(),
        }

        async def _get_session_state() -> dict:
            fresh = await runner.session_service.get_session(
                app_name=app.name,
                user_id="api_user",
                session_id=session.id,
            )
            return fresh.state if fresh and fresh.state is not None else {}

        async def _on_retry(agent_name: str, attempt: int) -> None:
            completed_agents.discard(agent_name)
            self._bigquery_repo.update_status(
                job_id,
                "PROCESSING",
                current_step=(
                    f"Retrying {agent_name} ({attempt}/{settings.AGENT_RETRY_ATTEMPTS})"
                ),
                metadata_update={
                    "current_agent": agent_name,
                    "agent_retry_attempt": attempt,
                },
            )

        async def _process_event(event: Any) -> None:
            log_event(
                event,
                verbose=settings.AGENT_EVENT_LOG_VERBOSE,
                log_file=settings.agent_event_log_path,
            )
            self._progress.process_event_milestones(
                event,
                job_id,
                total_agents,
                completed_agents,
                agent_descriptions,
                status_write_state=status_write_state,
            )

        try:
            await run_runner_with_per_agent_retry(
                runner,
                app_name=app.name,
                user_id="api_user",
                session_id=session.id,
                run_config=run_config,
                new_message=types.UserContent(
                    parts=[
                        types.Part(
                            text=(
                                f"Run the Sales Research Agent for the company "
                                f"{company_name}"
                            )
                        )
                    ]
                ),
                process_event=_process_event,
                get_session_state=_get_session_state,
                on_retry=_on_retry,
            )
        except AgentOutputError as e:
            logger.error(
                "Pipeline failed for agent %s after %s attempts: %s",
                e.agent_name,
                settings.AGENT_RETRY_ATTEMPTS,
                e,
            )
            raise ServiceError(str(e)) from e
        except Exception as e:
            logger.error(f"Final failure after retries: {e}")
            raise

    async def _get_or_create_runner_session(
        self, runner: Runner, app: Any, job_id: str, company_name: str, attempt: int
    ):
        """Helper to get or create a runner session."""
        session_id = runner_session_id(job_id, attempt)

        session = await runner.session_service.get_session(
            app_name=app.name,
            user_id="api_user",
            session_id=session_id,
        )
        if not session:
            session = await runner.session_service.create_session(
                app_name=app.name,
                user_id="api_user",
                session_id=session_id,
                state={
                    "company_name": company_name,
                    "job_execution_id": job_id,
                },
            )
        return session

    @staticmethod
    def _get_all_agents(agent: Any) -> list[Any]:
        agents = [agent]
        if hasattr(agent, "sub_agents") and agent.sub_agents:
            for sub in agent.sub_agents:
                agents.extend(ResearchRunnerService._get_all_agents(sub))
        return agents
