"""Domain contracts and schemas for research services."""

from .contracts import (
    AGENT_CONTRACTS,
    AGENT_OUTPUT_KEYS,
    DOMAIN_OUTPUT_KEYS,
    MIN_DOMAIN_OUTPUTS_REQUIRED,
    RESEARCH_AGENT_CONTRACTS,
    SYNTHESIS_AGENT_NAMES,
    AgentContract,
    get_agent_contract,
    get_output_key,
    is_tracked_agent,
    list_missing_domain_outputs,
    list_missing_research_outputs,
    validate_agent_output,
    validate_domain_outputs_present,
)
from .schemas import (
    CandidateQueries,
    ColtAlignmentMapping,
    ColtAlignmentOutput,
    NormalizedQueryPlan,
    QueryWithMetadata,
    StrategicOpportunitySummary,
    UseCaseRecommendation,
)

__all__ = [
    "AgentContract",
    "AGENT_CONTRACTS",
    "RESEARCH_AGENT_CONTRACTS",
    "SYNTHESIS_AGENT_NAMES",
    "AGENT_OUTPUT_KEYS",
    "DOMAIN_OUTPUT_KEYS",
    "MIN_DOMAIN_OUTPUTS_REQUIRED",
    "get_agent_contract",
    "get_output_key",
    "is_tracked_agent",
    "list_missing_research_outputs",
    "list_missing_domain_outputs",
    "validate_domain_outputs_present",
    "validate_agent_output",
    "QueryWithMetadata",
    "CandidateQueries",
    "NormalizedQueryPlan",
    "ColtAlignmentMapping",
    "UseCaseRecommendation",
    "StrategicOpportunitySummary",
    "ColtAlignmentOutput",
]
