"""ADK runner lifecycle for sales research jobs."""

from __future__ import annotations

from typing import Any

from google.adk.agents.run_config import RunConfig
from google.adk.artifacts.in_memory_artifact_service import InMemoryArtifactService
from google.adk.memory.in_memory_memory_service import InMemoryMemoryService
from google.adk.runners import Runner
from google.genai import types

from ....core.config import settings
from ....core.exceptions import AgentOutputError, ServiceError
from ....core.logging_config import logger
from ....repositories.bigquery_repository import BigQueryRepository
from ....utils.tracing import job_attrs, traced
from .event_log import log_event
from .progress import ResearchProgressTracker
from .resilience.runner_loop import run_runner_with_per_agent_retry
from .session_ids import runner_session_id
from .session_service import build_session_service
from .state_mutation import mutate_stored_session_state


class ResearchRunnerService:
    """Run the SalesAgent ADK graph and stream progress to BigQuery."""

    def __init__(
        self,
        bigquery_repository: BigQueryRepository,
        progress_tracker: ResearchProgressTracker | None = None,
    ) -> None:
        self._bigquery_repo = bigquery_repository
        self._progress = progress_tracker or ResearchProgressTracker(
            bigquery_repository
        )

    @traced("research.adk.run", attributes=job_attrs)
    async def run(
        self,
        job_id: str,
        company_name: str,
        attempt: int = 0,
    ) -> tuple[str, dict]:
        """Run the SalesAgent and return the final report and session state."""
        from opentelemetry import trace

        span = trace.get_current_span()
        span.set_attribute("research.session_id", runner_session_id(job_id, attempt))
        from ..graph import create_sales_agent_app

        app = create_sales_agent_app()
        session_service = build_session_service()
        runner = Runner(
            app=app,
            artifact_service=InMemoryArtifactService(),
            session_service=session_service,
            memory_service=InMemoryMemoryService(),
        )

        session = await self._get_or_create_runner_session(
            runner, app, job_id, company_name, attempt
        )

        try:
            await self.run_agents(runner, session, job_id, company_name, app)
        except AgentOutputError as e:
            if getattr(e, "error_class", None) != "REPORT_VALIDATION_FAILED":
                raise
            logger.error(
                f"[Validation] Report validation failed for job_id={job_id} "
                f"agent={e.agent_name}: {e}"
            )
            span.set_attribute("research.report_validation_status", "FAILED")
            session = await runner.session_service.get_session(
                app_name=app.name,
                user_id="api_user",
                session_id=session.id,
            )
            return "", dict(session.state if session and session.state else {})

        session = await runner.session_service.get_session(
            app_name=app.name,
            user_id="api_user",
            session_id=session.id,
        )
        final_report = session.state.get("final_report", "")

        if not final_report:
            logger.error(
                f"[Pipeline] No final report generated for job_id={job_id} "
                f"session_id={session.id}"
            )
            raise ServiceError("No final report generated by SalesAgent")

        logger.info(
            f"[Pipeline] Retrieved final report for job_id={job_id} "
            f"length={len(final_report)}"
        )
        span.set_attribute("research.final_report_length", len(final_report))
        return final_report, session.state

    @traced("research.adk.runner.lifecycle", attributes=job_attrs)
    async def run_agents(
        self,
        runner: Runner,
        session: Any,
        job_id: str,
        company_name: str,
        app: Any,
    ) -> None:
        """Execute the agent run with per-agent output validation and resume retries."""
        logger.info(
            f"[Pipeline] Starting agent run job_id={job_id} session_id={session.id} "
            f"company={company_name!r}"
        )
        run_config = RunConfig()

        all_agents = self._get_all_agents(app.root_agent)
        total_agents = len(all_agents)
        agent_descriptions = {a.name: a.description for a in all_agents}
        completed_agents: set[str] = set()

        status_write_state: dict[str, Any] = {
            "last_progress": None,
            "last_step": None,
            "last_write_ts": 0.0,
            "seen_authors": set(),
        }
        get_session_state = self._make_state_fetcher(runner, app.name, session.id)
        get_session = self._make_session_fetcher(runner, app.name, session.id)
        persist_state = self._make_state_persister(runner, app.name, session.id)
        on_retry = self._make_retry_handler(job_id, completed_agents)
        process_event = self._make_event_processor(
            job_id=job_id,
            total_agents=total_agents,
            completed_agents=completed_agents,
            agent_descriptions=agent_descriptions,
            status_write_state=status_write_state,
        )

        try:
            await run_runner_with_per_agent_retry(
                runner,
                app_name=app.name,
                user_id="api_user",
                session_id=session.id,
                run_config=run_config,
                new_message=self._initial_run_message(company_name),
                process_event=process_event,
                get_session_state=get_session_state,
                get_session=get_session,
                on_retry=on_retry,
                persist_state=persist_state,
                company_name=company_name,
            )
            logger.info(
                f"[Pipeline] Agent run completed job_id={job_id} "
                f"session_id={session.id}"
            )
        except AgentOutputError as e:
            if getattr(e, "error_class", None) == "REPORT_VALIDATION_FAILED":
                raise
            logger.error(
                f"[Pipeline] Failed for agent={e.agent_name} after "
                f"{settings.AGENT_RETRY_ATTEMPTS} attempts: {e}"
            )
            raise ServiceError(str(e)) from e
        except Exception as e:
            logger.error(f"[Pipeline] Final failure after retries job_id={job_id}: {e}")
            raise

    async def _get_or_create_runner_session(
        self, runner: Runner, app: Any, job_id: str, company_name: str, attempt: int
    ):
        """Helper to get or create a runner session."""
        session_id = runner_session_id(job_id, attempt)

        session = await runner.session_service.get_session(
            app_name=app.name,
            user_id="api_user",
            session_id=session_id,
        )
        if not session:
            logger.info(
                f"[Pipeline] Creating ADK session session_id={session_id} "
                f"job_id={job_id}"
            )
            session = await runner.session_service.create_session(
                app_name=app.name,
                user_id="api_user",
                session_id=session_id,
                state={
                    "company_name": company_name,
                    "job_execution_id": job_id,
                },
            )
        return session

    @staticmethod
    def _get_all_agents(agent: Any) -> list[Any]:
        agents = [agent]
        if hasattr(agent, "sub_agents") and agent.sub_agents:
            for sub in agent.sub_agents:
                agents.extend(ResearchRunnerService._get_all_agents(sub))
        return agents

    @staticmethod
    def _initial_run_message(company_name: str) -> types.Content:
        return types.UserContent(
            parts=[
                types.Part(
                    text=f"Run the Sales Research Agent for the company {company_name}"
                )
            ]
        )

    @staticmethod
    def _make_state_fetcher(
        runner: Runner,
        app_name: str,
        session_id: str,
    ):
        async def _get_session_state() -> dict:
            fresh = await runner.session_service.get_session(
                app_name=app_name,
                user_id="api_user",
                session_id=session_id,
            )
            return fresh.state if fresh and fresh.state is not None else {}

        return _get_session_state

    @staticmethod
    def _make_session_fetcher(
        runner: Runner,
        app_name: str,
        session_id: str,
    ):
        async def _get_session():
            return await runner.session_service.get_session(
                app_name=app_name,
                user_id="api_user",
                session_id=session_id,
            )

        return _get_session

    @staticmethod
    def _make_state_persister(
        runner: Runner,
        app_name: str,
        session_id: str,
    ):
        def _persist_state(mutator) -> bool:
            persisted = mutate_stored_session_state(
                runner.session_service,
                app_name=app_name,
                user_id="api_user",
                session_id=session_id,
                mutator=mutator,
            )
            if persisted:
                logger.debug(
                    f"[Persist] Session state patch applied session_id={session_id}"
                )
            else:
                logger.warning(
                    f"[Persist] Session state patch failed session_id={session_id}"
                )
            return persisted

        return _persist_state

    def _make_retry_handler(self, job_id: str, completed_agents: set[str]):
        async def _on_retry(agent_name: str, attempt: int) -> None:
            completed_agents.discard(agent_name)
            logger.info(
                f"[Retry] job_id={job_id} agent={agent_name} "
                f"attempt={attempt}/{settings.AGENT_RETRY_ATTEMPTS}"
            )
            self._bigquery_repo.update_status(
                job_id,
                "PROCESSING",
                current_step=(
                    f"Retrying {agent_name} ({attempt}/{settings.AGENT_RETRY_ATTEMPTS})"
                ),
                metadata_update={
                    "current_agent": agent_name,
                    "agent_retry_attempt": attempt,
                },
            )

        return _on_retry

    def _make_event_processor(
        self,
        *,
        job_id: str,
        total_agents: int,
        completed_agents: set[str],
        agent_descriptions: dict[str, str | None],
        status_write_state: dict[str, Any],
    ):
        async def _process_event(event: Any) -> None:
            log_event(
                event,
                verbose=settings.AGENT_EVENT_LOG_VERBOSE,
                log_file=settings.agent_event_log_path,
            )
            self._progress.process_event_milestones(
                event,
                job_id,
                total_agents,
                completed_agents,
                agent_descriptions,
                status_write_state=status_write_state,
            )

        return _process_event
